"""add_user_id_column

Revision ID: add_user_id_column
Revises: a5ff953e928b
Create Date: 2025-04-20 12:01:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = 'add_user_id_column'
down_revision: Union[str, None] = 'a5ff953e928b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('user_id', UUID(as_uuid=True), nullable=True, unique=True))
    op.create_index(op.f('ix_auth_users_user_id'), 'auth_users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_user_id'), table_name='auth_users')
    op.drop_column('auth_users', 'user_id')
    # ### end Alembic commands ###
